package com.jie.mapper.model;

public class LockRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_record.id
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock_record.lock_name
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    private String lockName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_record.id
     *
     * @return the value of lock_record.id
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_record.id
     *
     * @param id the value for lock_record.id
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock_record.lock_name
     *
     * @return the value of lock_record.lock_name
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    public String getLockName() {
        return lockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock_record.lock_name
     *
     * @param lockName the value for lock_record.lock_name
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    public void setLockName(String lockName) {
        this.lockName = lockName == null ? null : lockName.trim();
    }
}