package com.jie.mapper.mapper;

import com.jie.mapper.model.LockRecord;
import com.jie.mapper.model.LockRecordQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LockRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    long countByExample(LockRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int deleteByExample(LockRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int insert(LockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int insertSelective(LockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    List<LockRecord> selectByExampleWithRowbounds(LockRecordQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    List<LockRecord> selectByExample(LockRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    LockRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int updateByExampleSelective(@Param("record") LockRecord record, @Param("example") LockRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int updateByExample(@Param("record") LockRecord record, @Param("example") LockRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int updateByPrimaryKeySelective(LockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock_record
     *
     * @mbg.generated Thu Sep 15 18:38:39 CST 2022
     */
    int updateByPrimaryKey(LockRecord record);
}